version: '3.8'

services:
  proxy-api:
    build: .
    ports:
      - "80:80"
    depends_on:
      - overseer
      - hermes
    networks:
      - my-network

  overseer:
    image: mendhak/http-https-echo:31
    container_name: overseer
    environment:
        - HTTP_PORT=8888
        - DISABLE_REQUEST_LOGS=true
    ports:
        - "8081:8888"
    networks:
      - my-network

  hermes:
    image: mendhak/http-https-echo:31
    container_name: hermes
    environment:
        - HTTP_PORT=8888
        - DISABLE_REQUEST_LOGS=true
    ports:
        - "8082:8888"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
